[package]
name = "thunkmetrc-wrapper"
version = "0.2.0"
edition = "2021"

[dependencies]
thunkmetrc-client = { path = "../client", version = "0.2.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
